name: production
url: https://react-superadmin.web.app
protection_rules:
  required_reviewers:
    required_approving_review_count: 1
    dismiss_stale_reviews: true
    require_code_owner_reviews: false
  required_status_checks:
    strict: true
    contexts: []
  deployment_branch_policy:
    protected_branches: true
    custom_branch_policies: false
