name: staging
url: https://react-superadmin-staging.web.app
protection_rules:
  required_reviewers:
    required_approving_review_count: 0
    dismiss_stale_reviews: false
    require_code_owner_reviews: false
  required_status_checks:
    strict: false
    contexts: []
  deployment_branch_policy:
    protected_branches: false
    custom_branch_policies: true
