import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'index',
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'introduction',
        'installation',
        'quick-start',
        'examples/basic-usage',
      ],
    },
    {
      type: 'category',
      label: 'Features',
      items: [
        'features',
        'features/react-admin-comparison',
        'features/missing-components-plan',
        'features/data-providers',
        'features/components-reference',
        'features/hooks-reference',
        'features/implementation-checklist',
        'features/roadmap',
      ],
    },
    {
      type: 'category',
      label: 'App Configuration',
      items: [
        'components/admin',
        'components/resource',
        'components/custom-routes',
        'components/layout',
      ],
    },
    {
      type: 'category',
      label: 'Data Fetching',
      items: [
        'components/data-provider-setup',
        'components/querying-api',
        'components/supported-backends',
        'components/writing-data-provider',
        'components/use-data-provider',
        'components/use-get-list',
        'components/use-get-one',
        'components/use-get-many',
        'components/use-get-many-reference',
        'components/use-create',
        'components/use-update',
        'components/use-delete',
        'components/use-update-many',
        'components/use-delete-many',
        'components/use-infinite-get-list',
        'components/use-get-tree',
        'components/with-lifecycle-callbacks',
        'components/fetch-json',
      ],
    },
    {
      type: 'category',
      label: 'Security',
      items: [
        'components/auth-provider-setup',
        'components/supported-auth-backends',
        'components/writing-auth-provider',
        'components/authorization',
        'components/rbac',
        'components/authenticated',
        'components/can-access',
        'components/use-auth',
        'components/use-permissions',
        'components/use-can-access',
        'components/use-auth-provider',
        'components/add-refresh-auth-to-auth-provider',
        'components/add-refresh-auth-to-data-provider',
      ],
    },
    {
      type: 'category',
      label: 'List Page',
      items: [
        'components/resource-list',
        'components/list-base',
        'components/list-guesser',
        'components/infinite-list',
        'components/data-table',
        'components/datagrid',
        'components/datagrid-ag',
        'components/simple-list',
        'components/single-field-list',
        'components/editable-datagrid',
        'components/calendar',
        'components/scheduler',
        'components/tree',
        'components/tree-with-details',
        'components/search-bar',
        'components/filter-list',
        'components/filter-live-form',
        'components/filter-live-search',
        'components/saved-queries-list',
        'components/stacked-filters',
        'components/pagination',
        'components/sort-button',
        'components/select-columns-button',
        'components/count',
        'components/with-list-context',
        'components/use-list-context',
        'components/use-list',
        'components/use-list-controller',
        'components/use-unselect',
        'components/use-unselect-all',
      ],
    },
    {
      type: 'category',
      label: 'Creation & Edition Pages',
      items: [
        'components/resource-form',
        'components/create-base',
        'components/edit-base',
        'components/edit-guesser',
        'components/simple-form',
        'components/tabbed-form',
        'components/long-form',
        'components/accordion-form',
        'components/wizard-form',
        'components/form',
        'components/toolbar',
        'components/save-button',
        'components/edit-dialog',
        'components/edit-in-dialog-button',
        'components/create-dialog',
        'components/create-in-dialog-button',
        'components/json-schema-form',
        'components/auto-persist-in-store',
        'components/auto-save',
        'components/form-filler-button',
        'components/use-create-context',
        'components/use-edit-context',
        'components/use-create-controller',
        'components/use-edit-controller',
        'components/use-save-context',
        'components/use-record-from-location',
        'components/use-register-mutation-middleware',
        'components/use-unique',
      ],
    },
    {
      type: 'category',
      label: 'Show Page',
      items: [
        'components/show',
        'components/show-base',
        'components/show-guesser',
        'components/simple-show-layout',
        'components/tabbed-show-layout',
        'components/labeled',
        'components/show-dialog',
        'components/show-in-dialog-button',
        'components/use-show-context',
        'components/use-show-controller',
      ],
    },
    {
      type: 'category',
      label: 'Common',
      items: [
        'components/with-record',
        'components/use-record-context',
        'components/use-get-record-id',
        'components/use-notify',
        'components/use-redirect',
        'components/use-refresh',
      ],
    },
    {
      type: 'category',
      label: 'Fields',
      items: [
        'components/array-field',
        'components/boolean-field',
        'components/chip-field',
        'components/date-field',
        'components/email-field',
        'components/file-field',
        'components/function-field',
        'components/image-field',
        'components/markdown-field',
        'components/number-field',
        'components/record-field',
        'components/reference-field',
        'components/reference-array-field',
        'components/reference-many-field',
        'components/reference-many-count',
        'components/reference-many-to-many-field',
        'components/reference-one-field',
        'components/rich-text-field',
        'components/select-field',
        'components/text-field',
        'components/translatable-fields',
        'components/url-field',
        'components/wrapper-field',
        'components/use-field-value',
      ],
    },
    {
      type: 'category',
      label: 'Inputs',
      items: [
        'components/array-input',
        'components/autocomplete-input',
        'components/autocomplete-array-input',
        'components/boolean-input',
        'components/checkbox-group-input',
        'components/date-input',
        'components/date-range-input',
        'components/datetime-input',
        'components/dual-list-input',
        'components/file-input',
        'components/image-input',
        'components/in-place-editor',
        'components/markdown-input',
        'components/nullable-boolean-input',
        'components/number-input',
        'components/password-input',
        'components/predictive-text-input',
        'components/radio-button-group-input',
        'components/reference-input',
        'components/reference-array-input',
        'components/reference-many-input',
        'components/reference-many-to-many-input',
        'components/reference-node-input',
        'components/reference-one-input',
        'components/rich-text-input',
        'components/search-input',
        'components/select-input',
        'components/select-array-input',
        'components/simple-form-iterator',
        'components/smart-rich-text-input',
        'components/text-array-input',
        'components/text-input',
        'components/textarea-input',
        'components/time-input',
        'components/translatable-inputs',
        'components/tree-input',
        'components/use-input',
      ],
    },
    {
      type: 'category',
      label: 'Preferences',
      items: [
        'components/use-store',
        'components/use-remove-from-store',
        'components/use-reset-store',
        'components/configurable',
        'components/use-store-context',
      ],
    },
    {
      type: 'category',
      label: 'I18N Provider and Translations',
      items: [
        'components/i18n-setup',
        'components/supported-locales',
        'components/translating-ui-components',
        'components/translate',
        'components/use-translate',
        'components/use-locale-state',
        'components/locales-menu-button',
      ],
    },
    {
      type: 'category',
      label: 'Other UI components',
      items: [
        'components/layout',
        'components/container-layout',
        'components/horizontal-menu',
        'components/solar-layout',
        'components/header',
        'components/sidebar',
        'components/multi-level-menu',
        'components/icon-menu',
        'components/title',
        'components/breadcrumb',
        'components/search',
        'components/search-with-result',
        'components/modal',
        'components/button',
        'components/revisions-button',
        'components/check-for-application-update',
        'components/record-representation',
        'components/prev-next-buttons',
        'components/use-define-app-location',
        'components/use-get-record-representation',
      ],
    },
    {
      type: 'category',
      label: 'Theming',
      items: [
        'components/sx-prop',
        'components/application-theme',
        'components/box-stack-grid',
        'components/toggle-theme-button',
        'components/use-media-query',
        'components/use-theme',
      ],
    },
    {
      type: 'category',
      label: 'Realtime',
      items: [
        'components/realtime-setup',
        'components/use-publish',
        'components/use-subscribe',
        'components/use-subscribe-callback',
        'components/use-subscribe-to-record',
        'components/use-subscribe-to-record-list',
        'components/use-lock',
        'components/use-unlock',
        'components/use-get-lock',
        'components/use-get-lock-live',
        'components/use-get-locks',
        'components/use-get-locks-live',
        'components/use-lock-on-mount',
        'components/use-lock-on-call',
        'components/use-get-list-live',
        'components/use-get-one-live',
        'components/list-live-update',
        'components/edit-live',
        'components/show-live',
        'components/menu-live',
      ],
    },
    {
      type: 'category',
      label: 'Developer',
      items: [
        'developer/api',
        'developer/architecture',
        'developer/ci-cd',
        'developer/components',
        'developer/contributing',
        'developer/cursor-rules',
        'developer/cursor-rules-quick-reference',
        'developer/environments',
        'developer/hooks',
        'developer/setup',
        'developer/testing',
        'developer/utilities',
      ],
    },
  ],
};

export default sidebars;
