import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'index',
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'introduction',
        'installation',
        'quick-start',
        'examples/basic-usage',
      ],
    },
    {
      type: 'category',
      label: 'Features',
      items: [
        'features',
        'features/react-admin-comparison',
        'features/missing-components-plan',
        'features/data-providers',
        'features/components-reference',
        'features/hooks-reference',
        'features/implementation-checklist',
        'features/roadmap',
      ],
    },
    {
      type: 'category',
      label: 'App Configuration',
      items: [
        'components/admin',
        'components/resource',
        'components/custom-routes',
      ],
    },
    {
      type: 'category',
      label: 'List Page',
      items: [
        'components/resource-list',
        'components/data-table',
        'components/pagination',
        'components/search-bar',
        'components/simple-list',
        'components/calendar',
        'components/tree',
        'components/tree-with-details',
        'components/datagrid-ag',
        'components/single-field-list',
        'components/editable-datagrid',
        'components/scheduler',
        'components/filter-list',
        'components/filter-live-form',
        'components/filter-live-search',
        'components/saved-queries-list',
        'components/stacked-filters',
        'components/sort-button',
        'components/select-columns-button',
        'components/count',
        'components/with-list-context',
      ],
    },
    {
      type: 'category',
      label: 'Creation & Edition Pages',
      items: [
        'components/resource-form',
        'components/simple-form',
        'components/tabbed-form',
        'components/form',
        'components/create-base',
        'components/edit-base',
        'components/edit-guesser',
        'components/long-form',
        'components/accordion-form',
        'components/wizard-form',
        'components/edit-dialog',
        'components/edit-in-dialog-button',
        'components/create-dialog',
        'components/create-in-dialog-button',
        'components/json-schema-form',
        'components/auto-persist-in-store',
        'components/form-filler-button',
      ],
    },
    {
      type: 'category',
      label: 'Show Page',
      items: [
        'components/show',
        'components/show-base',
        'components/show-guesser',
        'components/simple-show-layout',
        'components/tabbed-show-layout',
        'components/show-dialog',
        'components/show-in-dialog-button',
      ],
    },
    {
      type: 'category',
      label: 'Fields',
      items: [
        'components/array-field',
        'components/boolean-field',
        'components/date-field',
        'components/file-field',
        'components/function-field',
        'components/markdown-field',
        'components/number-field',
        'components/record-field',
        'components/reference-field',
        'components/reference-many-count',
        'components/reference-many-to-many-field',
        'components/reference-one-field',
        'components/rich-text-field',
        'components/select-field',
        'components/text-field',
        'components/translatable-fields',
        'components/wrapper-field',
      ],
    },
    {
      type: 'category',
      label: 'Inputs',
      items: [
        'components/array-input',
        'components/autocomplete-input',
        'components/autocomplete-array-input',
        'components/boolean-input',
        'components/checkbox-group-input',
        'components/date-input',
        'components/date-range-input',
        'components/dual-list-input',
        'components/file-input',
        'components/image-input',
        'components/in-place-editor',
        'components/markdown-input',
        'components/nullable-boolean-input',
        'components/number-input',
        'components/password-input',
        'components/predictive-text-input',
        'components/radio-button-group-input',
        'components/reference-input',
        'components/reference-array-input',
        'components/reference-many-input',
        'components/reference-many-to-many-input',
        'components/reference-node-input',
        'components/reference-one-input',
        'components/rich-text-input',
        'components/search-input',
        'components/select-input',
        'components/select-array-input',
        'components/simple-form-iterator',
        'components/smart-rich-text-input',
        'components/text-array-input',
        'components/text-input',
        'components/textarea-input',
        'components/time-input',
        'components/translatable-inputs',
        'components/tree-input',
      ],
    },
    {
      type: 'category',
      label: 'Other UI components',
      items: [
        'components/layout',
        'components/container-layout',
        'components/horizontal-menu',
        'components/solar-layout',
        'components/appbar',
        'components/sidebar',
        'components/multi-level-menu',
        'components/icon-menu',
        'components/breadcrumb',
        'components/search',
        'components/search-with-result',
        'components/modal',
        'components/button',
        'components/revisions-button',
        'components/check-for-application-update',
        'components/record-representation',
        'components/prev-next-buttons',
      ],
    },
    {
      type: 'category',
      label: 'Theming',
      items: [
        'components/box-stack-grid',
        'components/toggle-theme-button',
      ],
    },
    {
      type: 'category',
      label: 'Preferences',
      items: [
        'components/configurable',
      ],
    },
    {
      type: 'category',
      label: 'I18N Provider and Translations',
      items: [
        'components/translate',
        'components/locales-menu-button',
      ],
    },
    {
      type: 'category',
      label: 'Realtime',
      items: [
        'components/list-live-update',
        'components/edit-live',
        'components/show-live',
        'components/menu-live',
      ],
    },
    {
      type: 'category',
      label: 'Developer',
      items: [
        'developer/architecture',
        'developer/components',
        'developer/hooks',
        'developer/utilities',
        'developer/environments',
        'developer/testing',
        'developer/cursor-rules',
        'developer/cursor-rules-quick-reference',
        'developer/ci-cd',
        'developer/contributing',
      ],
    },
  ],
};

export default sidebars;
