import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'index',
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'introduction',
        'installation',
        'quick-start',
        'examples/basic-usage',
      ],
    },
    {
      type: 'category',
      label: 'Features',
      items: [
        'features',
        'features/data-providers',
        'features/roadmap',
        'features/components-reference',
        'features/hooks-reference',
        'features/implementation-checklist',
      ],
    },
    {
      type: 'category',
      label: 'Components',
      items: [
        'components/button',
        'components/card',
        'components/modal',
        'components/badge',
        'components/dropdown',
        'components/alert',
        'components/tooltip',
        'components/select-input',
        'components/date-input',
        'components/boolean-input',
        'components/number-input',
        'components/password-input',
        'components/label',
        'components/array-input',
        'components/autocomplete-input',
        'components/reference-field',
        'components/checkbox-input',
        'components/checkbox-group-input',
        'components/textarea-input',
        'components/text-input',
        'components/input',
        'components/form',
        'components/forms',
        'components/layout',
        'components/admin',
        'components/tooltip',
        'components/appbar',
      ],
    },
    {
      type: 'category',
      label: 'CRUD Components',
      items: [
        'components/data-table',
        'components/pagination',
        'components/resource-form',
        'components/resource-list',
        'components/search-bar',
      ],
    },
    {
      type: 'category',
      label: 'Layout Components',
      items: [
        'components/header',
        'components/sidebar',
        'components/footer',
        'components/admin-layout',
      ],
    },
    {
      type: 'category',
      label: 'Developer',
      items: [
        'developer/architecture',
        'developer/components',
        'developer/hooks',
        'developer/utilities',
        'developer/environments',
        'developer/testing',
        'developer/cursor-rules',
        'developer/cursor-rules-quick-reference',
        'developer/ci-cd',
        'developer/contributing',
      ],
    },
  ],
};

export default sidebars;
