name: Docs Build (develop) [deprecated]

on:
  push:
    branches-ignore: ['**']
  pull_request:
    branches-ignore: ['**']

jobs:
  build-docs:
    if: false
    name: Disabled - use .github/workflows/deploy.yml
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Use deploy.yml for all docs builds and deploys'
